### ISSUE TITLE
magneticio/mesos:0.22.0 docker images is not published

### ISSUE THREAD

**Issue by vlesierse** [magneticio/vamp-docker-images#1]
The docker-compose.yml references `magneticio/mesos:0.22.0` which isn't published to the public docker registry.

**Comment by tnolet** [comment]
Good catch. Pushing it as we speak. If you are in a hurry you can clone this repo and build it at https://github.com/magneticio/vamp-docker/tree/master/dockerfiles/mesos

**Comment by vlesierse** [comment]
Thnx, got it running :+1:
