### ISSUE TITLE
Can't find the base image in the docker hub

### ISSUE THREAD

**Issue by sotuzun** [magneticio/vamp-docker-images#17]
I guess, you haven't pushed magneticio/vamp-clique-zookeeper image yet? Gives me error when I build clique-zookeeper-marathon.

**Comment by dragoslav** [comment]
We don't push updates of those images often. If you build from the source the best is to build dependencies as well (https://github.com/magneticio/vamp-docker-images#example-1-building-vamp-quick-start).

**Comment by olafmol** [comment]
closing this for now after explanation of build proces by @dragoslav. @sotuzun please re-open if still relevant.
