### ISSUE TITLE
Unifying buildserver and packer

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-docker-images#20]
**Project interface** 

What developers should provide in their repositories:

1) `make build` - full clean build without storing deliverable 
2) `make pack` - minimal action to store deliverable(s) to what is currently the `packer` volume (e.g. without running tests)
3) `make` - full clean build with storing deliverable(s) - i.e. `make build pack`

**Build scenarios**

1) Building all Vamp images (`quick-start`, `vamp-dcos`, `vamp-workflow-agent`, `vamp-runner`...) without any other app/lib dependency a part of having Docker installed (no git as well). There should be no touching of local file system and all files should stay inside the container (i.e. temporally) - only result of successful build should be a new Docker image.

2) Building all Vamp images with local source - similar as 1) just now project source is not checked out from the remote repositories but provided by mounting directories. Project source dir should not be changed in any way after the build.

3) Building with local dependency cache - related to `.ivy2`, `.sbt`, `node_modules, `GOPATH` etc.

4) Building with source 2) and dependency cache 3)

**Build stages**

1) By default full build&pack, but with option to specify just specific action (e.g. `make pack`)
2) Getting deliverables from `packer` volume and creating the Docker images

By default both 1) and 2) should be invoked but there should be an option to invoke just a single one.

**Additional notes**
1) New good name from buildserver + packer single repository and consequentially volume name change etc.

**Comment by iamtew** [comment]
https://github.com/magneticio/buildserver/issues/5

**Comment by iamtew** [comment]
Buildserver and packer have been merged together.
Following projects are currently building using the buildserver:
- https://github.com/magneticio/vamp/
- https://github.com/magneticio/vamp-ui/
- https://github.com/magneticio/vamp-gateway-agent/
- https://github.com/magneticio/vamp-workflow-agent/

Remainder work is to migrate all the building of the other images over to the use of the buildserver as well, that includes all images covered under this project, vamp-docker-images.
