### ISSUE TITLE
metricbeat error messages in error log of Katana 094  DCOS

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-docker-images#35]
(AT BEGINNING OF FILE)
I0410 22:15:36.046849  5629 exec.cpp:162] Version: 1.2.1
I0410 22:15:36.051479  5636 exec.cpp:237] Executor registered on agent 72a48eab-6a37-4e73-b2a6-26ba64d9d0e3-S2
WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
/sbin/runsvdir started
runsv metricbeat: fatal: unable to start ./run: exec format error

**Comment by ItsMeijers** [comment]
Fixed by 66ed3a0
