### ISSUE TITLE
vamp deployment fails if mariadb is not ready

### ISSUE THREAD

**Issue by jzubielik** [magneticio/vamp-docker-images#59]

**Comment by jason-magnetic-io** [comment]
@jzubielik can this be closed?

**Comment by jzubielik** [comment]
@jason-magnetic-io It depends. I fixed services deployment in `tests/dcos/dcos-acs.sh` to wait for MySQL to be deployed before ES and Vamp, but f.e. Vamp is waiting for ES to be ready even if it's started first. It could do the same for MySQL especially if it depends upon it.
From the pipeline point of view it can be closed after closing #66 and if Jenkins will be able to produce and test the katana images.
